@server=https://ominous-space-dollop-wr5wr59pxprgf569j-3000.app.github.dev

### Criação de Receita
POST {{server}}/api/receitas
Content-Type: application/json

{
    "img": "images/nigiri_salmao.jpg",
    "tag": "Salgada",
    "title": "Nigiri de Salmão",
    "time": "10 min",
    "servings": 1,
    "author": "Paulo Benetton",
    "ingredients": [
      "50 gramas de Arroz Japonês",
      "80 gramas de Salmão Cru",
      "Sal",
      "Vinagre de Arroz",
      "Açúcar"
    ],
    "steps": [
      "Lave o arroz com água até ela sair transparente",
      "Tempere o arroz com uma mistura de uma pitada de sal, uma colher de sopa de açúcar, deixe descansar por 5 minutos",
      "Corte a peça de salmão na diagonal",
      "Monte o nigiri moldando o arroz com as mãos e posicione o salmão no topo"
    ]
}

### Ler as Receitas
GET {{server}}/api/receitas


### Ler uma Receita específica a partir do ID
GET {{server}}/api/receitas/9b26577f-dfcb-4f68-b847-dac7b2d2f435


### Alterar uma receita específica
PUT {{server}}/api/receitas/9b26577f-dfcb-4f68-b847-dac7b2d2f435
Content-Type: application/json

{
    "id": "9b26577f-dfcb-4f68-b847-dac7b2d2f435",
    "img": "images/salada.png",
    "tag": "Vegana",
    "title": "Salada Tropical",
    "time": "15 min",
    "servings": 2,
    "author": "Gabriela Carvalho",
    "ingredients": [
      "Alface",
      "Tomate cereja",
      "Pepino",
      "Cebola",
      "Manga",
      "Maçã",
      "Azeite e sal"
    ],
    "steps": [
      "Lave os ingredientes",
      "Corte tudo",
      "Tempere e sirva"
    ]
  }

### Remover uma receita pelo ID
DELETE {{server}}/api/receitas/9b26577f-dfcb-4f68-b847-dac7b2d2f435
